export default {
  ILLEGAL: 'ILLEGAL',
  EOF: 'EOF',
  LET: 'LET',
  VAR: 'VAR',
  CONST: 'CONST',
  IDENTIFIER: 'IDENTIFIER',
  ASSIGN_SIGN: 'ASSIGN_SIGN',
  PLUS_SIGN: 'PLUS_SIGN',
  NUMBER: 'NUMBER',
  SEMICOLON: 'SEMICOLON',
  NEWLINE: 'NEWLINE',
  STRING: 'STRING',
  EQ: 'EQ',
  NOT_EQ: 'NOT_EQ',
  IF: 'IF',
  ELSE: 'ELSE',

  FOR: 'FOR',
  IN: 'IN',

  INC_DEC: 'INC_DEC',
  COLON: 'COLON',

  DOT: 'DOT',
  LEFT_SQUARE_BRACKET: 'LEFT_SQUARE_BRACKET',
  RIGHT_SQUARE_BRACKET: 'RIGHT_SQUARE_BRACKET',

  MINUS_SIGN: 'MINUS_SIGN',
  BANG_SIGN: 'BANG_SIGN',
  ASTERISK: 'ASTERISK',
  SLASH: 'SLASH',
  LT: 'LT',
  GT: 'GT',
  COMMA: 'COMMA',

  FUNCTION: 'FUNCTION',
  TRUE: 'TRUE',
  FALSE: 'FALSE',
  RETURN: 'RETURN',

  LEFT_BRACE: 'LEFT_BRACE',
  RIGHT_BRACE: 'RIGHT_BRACE',
  LEFT_PARENT: 'LEFT_PARENT',
  RIGHT_PARENT: 'RIGHT_PARENT',

  DEBUGGER: 'DEBUGGER',
  WITH: 'WITH',
  CONTINUE: 'CONTINUE',
  BREAK: 'BREAK',

  SWITCH: 'SWITCH',
  CASE: 'CASE',
  DEFAULT: 'DEFAULT',

  THROW: 'THROW',
  TRY: 'TRY',
  CATCH: 'CATCH',
  FINALLY: 'FINALLY',

  WHILE: 'WHILE',
  DO: 'DO',
}
